//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attestation
    {
        public int SubjectSpecialityId { get; set; }
        public int SyllabusId { get; set; }
        public int AttestationFormId { get; set; }
        public string Qty { get; set; }
    
        public virtual AttestationForm AttestationForm { get; set; }
        public virtual SubjectSpeciality SubjectSpeciality { get; set; }
        public virtual Syllabu Syllabu { get; set; }
    }
}
