//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeApp.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CollegeBaseEntities : DbContext
    {
        private static CollegeBaseEntities _context;
        public CollegeBaseEntities()
            : base("name=CollegeBaseEntities")
        {
        }

        public static CollegeBaseEntities GetContext()
        {
            if (_context == null)
                _context = new CollegeBaseEntities();

            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attestation> Attestations { get; set; }
        public virtual DbSet<AttestationForm> AttestationForms { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<LoadType> LoadTypes { get; set; }
        public virtual DbSet<Professor> Professors { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Speciality> Specialities { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<SubjectCategory> SubjectCategories { get; set; }
        public virtual DbSet<SubjectIndex> SubjectIndexes { get; set; }
        public virtual DbSet<SubjectLoad> SubjectLoads { get; set; }
        public virtual DbSet<SubjectProfessor> SubjectProfessors { get; set; }
        public virtual DbSet<SubjectSemester> SubjectSemesters { get; set; }
        public virtual DbSet<SubjectSpeciality> SubjectSpecialities { get; set; }
        public virtual DbSet<Syllabu> Syllabus { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
