//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectSpeciality
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubjectSpeciality()
        {
            this.Attestations = new HashSet<Attestation>();
            this.SubjectSemesters = new HashSet<SubjectSemester>();
        }
    
        public int Id { get; set; }
        public int SubjectId { get; set; }
        public string SpecialityId { get; set; }
        public int CategoryId { get; set; }
        public int IndexName { get; set; }
        public int QualificationId { get; set; }
        public int StartYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attestation> Attestations { get; set; }
        public virtual Qualification Qualification { get; set; }
        public virtual Speciality Speciality { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual SubjectCategory SubjectCategory { get; set; }
        public virtual SubjectIndex SubjectIndex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectSemester> SubjectSemesters { get; set; }
    }
}
