//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control.Test.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectSemester
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubjectSemester()
        {
            this.SubjectLoads = new HashSet<SubjectLoad>();
            this.SubjectProfessors = new HashSet<SubjectProfessor>();
        }
    
        public int Id { get; set; }
        public int SubjectSpecialityId { get; set; }
        public int Semester { get; set; }
        public int SyllabusId { get; set; }
        public int TotalQtyHours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectLoad> SubjectLoads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectProfessor> SubjectProfessors { get; set; }
        public virtual SubjectSpeciality SubjectSpeciality { get; set; }
        public virtual Syllabu Syllabu { get; set; }
    }
}
